In [2]:
data = [[0.4398441247, 0.1368689254 ,0.0467829011],
 [0.4036561562, 0.1682101770 ,0.0467829011],
 [0.2960946225, 0.0965374390 ,0.1041744267],
 [0.4128355623, 0.1290350505 ,0.0561125443],
 [0.4222647902, 0.0922505624 ,0.0688059715],
 [0.3687343884, 0.1924528769 ,0.0286921127],
 [0.3426255515, 0.2535254898 ,0.0634729908],
 [0.4704129646, 0.4812483214 ,0.0215803535],
 [0.4002898522, 0.5160960117 ,0.0220685989],
 [0.2306079942, 0.2705043098 ,0.0394796293],
 [0.2096982459, 0.5870259864 ,0.0280204478],
 [0.0692592763, 0.0003253104 ,0.5592124298],
 [0.0042579845, 0.0051200632 ,0.8373503326],
 [0.0041238353, 0.0051763625 ,0.8331479697],
 [0.0022091512, 0.0024702886 ,0.8405247746],
 [0.0016769227, 0.0108900310 ,0.5388359381],
 [0.0008715342, 0.2577581105 ,0.4968188878],
 [0.0010659423, 0.0347353373 ,0.3979115888],
 [0.0010174755, 0.3063534264 ,0.3855305801],
 [0.3735611385, 0.0115540175 ,0.2309774635],
 [0.3467293291, 0.0102884863 ,0.2703310156],
 [0.0395913869, 0.0057575426 ,0.2945262279],
 [0.0123818247, 0.0096151677 ,0.2720348040],
 [0.0092978885, 0.0338528379 ,0.2616777893],
 [0.0119871865, 0.0314622583 ,0.2617218908],
 [0.0098196503, 0.1527738935 ,0.2039974156],
 [0.0754253617, 0.0048745661 ,0.3740806552],
 [0.0244442529, 0.0065128341 ,0.5358350442],
 [0.0556134977, 0.0025145045 ,0.4994430086],
 [0.3168085177, 0.0029939616 ,0.4771956451],
 [0.0181229038, 0.0077439461 ,0.5887376109],
 [0.0368090323, 0.2496285025 ,0.1910278568],
 [0.0114498088, 0.0258337239 ,0.3108568816],
 [0.9861235461, 0.0301037203 ,0.0418462362],
 [0.6918248878, 0.0603702430 ,0.0883896015],
 [0.7828099853, 0.0680940740 ,0.0671564338],
 [0.8052780288, 0.1265409544 ,0.0168030732],
 [0.9952559658, 0.1027874944 ,0.0328832847],
 [0.0809335518, 0.0886042556 ,0.1171346336],
 [0.0731513109, 0.1099698430 ,0.1643631680],
 [0.3652159608, 0.1826788500 ,0.0878052628],
 [0.1706531380, 0.0838665806 ,0.1939715996],
 [0.2037641260, 0.3474821127 ,0.0817007380],
 [0.1924971871, 0.1883486931 ,0.0898883344],
 [0.1023732245, 0.4097029870 ,0.0893734288],
 [0.0618471138, 0.2409151280 ,0.1315551304],
 [0.0754036458, 0.4552052614 ,0.1274742927],
 [0.0760867003, 0.3061547238 ,0.1197030610],
 [0.0418700849, 0.7776677554 ,0.1162250295],
 [0.0427775988, 0.6980851699 ,0.1056383479],
 [0.0486167365, 0.6436595427 ,0.0998406028]]


data

[[0.4398441247, 0.1368689254, 0.0467829011],
 [0.4036561562, 0.168210177, 0.0467829011],
 [0.2960946225, 0.096537439, 0.1041744267],
 [0.4128355623, 0.1290350505, 0.0561125443],
 [0.4222647902, 0.0922505624, 0.0688059715],
 [0.3687343884, 0.1924528769, 0.0286921127],
 [0.3426255515, 0.2535254898, 0.0634729908],
 [0.4704129646, 0.4812483214, 0.0215803535],
 [0.4002898522, 0.5160960117, 0.0220685989],
 [0.2306079942, 0.2705043098, 0.0394796293],
 [0.2096982459, 0.5870259864, 0.0280204478],
 [0.0692592763, 0.0003253104, 0.5592124298],
 [0.0042579845, 0.0051200632, 0.8373503326],
 [0.0041238353, 0.0051763625, 0.8331479697],
 [0.0022091512, 0.0024702886, 0.8405247746],
 [0.0016769227, 0.010890031, 0.5388359381],
 [0.0008715342, 0.2577581105, 0.4968188878],
 [0.0010659423, 0.0347353373, 0.3979115888],
 [0.0010174755, 0.3063534264, 0.3855305801],
 [0.3735611385, 0.0115540175, 0.2309774635],
 [0.3467293291, 0.0102884863, 0.2703310156],
 [0.0395913869, 0.0057575426, 0.2945262279],
 [0.012381824

In [13]:
from pymoo.indicators.hv.exact import ExactHypervolume
import numpy as np
hv = ExactHypervolume(3*[11]).add(np.array(data))
from moda import HSSParameters, HSSSolver,DataSet
import moda
ds = DataSet(np.array(data))
solver = HSSSolver()
params = HSSParameters()
params.Strategy = moda.SubsetSelectionStrategy.Decremental
params.StoppingSize = 1
print(solver.Solve(ds, params))
remaining_indices = np.arange(len(data)) 
for i in range(20):
    k = hv.hvc.argmin()
    hv.delete(k)
    removed_original_index = remaining_indices[k]
    print(removed_original_index)
    remaining_indices = np.delete(remaining_indices, k)
    print(hv.F)

([], 0.0)
12
[[4.39844125e-01 1.36868925e-01 4.67829011e-02]
 [4.03656156e-01 1.68210177e-01 4.67829011e-02]
 [2.96094623e-01 9.65374390e-02 1.04174427e-01]
 [4.12835562e-01 1.29035050e-01 5.61125443e-02]
 [4.22264790e-01 9.22505624e-02 6.88059715e-02]
 [3.68734388e-01 1.92452877e-01 2.86921127e-02]
 [3.42625552e-01 2.53525490e-01 6.34729908e-02]
 [4.70412965e-01 4.81248321e-01 2.15803535e-02]
 [4.00289852e-01 5.16096012e-01 2.20685989e-02]
 [2.30607994e-01 2.70504310e-01 3.94796293e-02]
 [2.09698246e-01 5.87025986e-01 2.80204478e-02]
 [6.92592763e-02 3.25310400e-04 5.59212430e-01]
 [4.12383530e-03 5.17636250e-03 8.33147970e-01]
 [2.20915120e-03 2.47028860e-03 8.40524775e-01]
 [1.67692270e-03 1.08900310e-02 5.38835938e-01]
 [8.71534200e-04 2.57758111e-01 4.96818888e-01]
 [1.06594230e-03 3.47353373e-02 3.97911589e-01]
 [1.01747550e-03 3.06353426e-01 3.85530580e-01]
 [3.73561139e-01 1.15540175e-02 2.30977464e-01]
 [3.46729329e-01 1.02884863e-02 2.70331016e-01]
 [3.95913869e-02 5.75754260